### ISSUE TITLE
npm run dev fail

### ISSUE THREAD

**Issue by lzysuqianqiu** [makunet/maku-admin#1]
> maku-admin@2.0.0 dev
> vite

file:///D:/github/front/maku-admin/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
    at async link (internal/modules/esm/module_job.js:42:21)

**Comment by ibabamu** [comment]
nodejs使用16.x
